### ISSUE TITLE
Reconnection interval

### ISSUE THREAD

**Issue by trisk** [dc297/mqttclpro#14]
If I restart the broker, the app often reconnects too frequently (like, once per second) instead of using the configured interval and gets blacklisted by the broker (hbmqtt) but continues to try to reconnect forever.

**Comment by dc297** [comment]
Let me try and setup the hbmqtt broker on my system and test how it goes.

**Comment by dc297** [comment]
Hey can you share your configuration file for the broker?

**Comment by trisk** [comment]
I'm using the instance of hbmqtt 0.8 embedded in Home Assistant (https://home-assistant.io/docs/mqtt/broker/).

It generates the following config here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/mqtt/server.py

```python
    {
        'listeners': {
            'default': {
                'max-connections': 50000,
                'bind': '0.0.0.0:1883',
                'type': 'tcp',
            },
            'ws-1': {
                'bind': '0.0.0.0:8080',
                'type': 'ws',
            },
        },
        'auth': {
            'allow-anonymous': False,
            'password-file': '<temp file containing "homeassistant:passing encrypted password>'
        },
        'plugins': ['auth_anonymous', 'auth_file'],
    }
```

IIRC one way to enter the state where app reconnects too quickly and gets blacklisted by the broker is to enter an incorrect username/password, though it also happens during normal operation.

**Comment by dc297** [comment]
I have observed that the issue occurs only while using hbmqtt. Can you confirm if similar issue is observed with mosquito or hivemq?

**Comment by motir** [comment]
Hey,

Thanks for a wonderful plugin!

Not sure if I'm seeing the same error described by OP or maybe it's a different one.

I'm using homeassistant, too, with the embedded hbmqtt broker (installed on a pi).
Tasker and mqttclpro are installed on an Android TV box.

When I restart the broker, connection is never restored. When I launch mqttclpro manually, I see it scheduled a retry for later, but this retry also fails. Only when I get into the settings page and then get back to the main menu, it retries to connect and succeeds. Tried setting the retry interval to 1 sec but it doesn't seem like it influences anything.

I'm not sure this is due to homeassistant blacklisting the connection, b/c when I manually do the settings in/out trick - connection is done ok. Would have expected it to fail if it was the broker that refused connection. This is probably some internal bug with mqttclpro?

What do you think? Is that the same issue or a different one? Should I open another ticket?

I can provide log files if needed, for both the client and the server (how do I see logfiles for mqttclpro?).
Just LMK what you need.

Cheers!
Moti

**Comment by dc297** [comment]
Hey thanx for such a detailed explanation of the issue. I'll try to simulate and fix the issue over the weekend.

I'll let you know if the log files are required.

Cheers!

**Comment by dc297** [comment]
Hey I have tweaked some settings in the latest version. Do check it out and let me know if the issue is fixed.

Cheers

**Comment by motir** [comment]
Hi. Thanks.
Tried it.
Looks like it's still the same - once a connection is not possible ("failed to connect") the scheduled reconnection never occurs. I set retry to 10 seconds but it did not retry so connection was not established until I manually forced it (by going into the settings page, changing a param and going back to the main menu).

**Comment by dc297** [comment]
Hey. Try increasing the retry interval to 30 seconds. Android doesn't like short intervals like 10 seconds.

**Comment by motir** [comment]
I tried.
Still doesn't try to reconnect.

To reproduce:
1. Make sure it's connected to a broker
2. Shut down the broker
3. It will say "disconnected, retry at..."
4. Keep the broker down
5. mqttclpro doesn't retry...

Note re step 4: maybe it retries but because the broker is still down
something happens and it doesn't display the retry + doesn't try again?
This is just a theory.




- Moti

**Comment by dc297** [comment]
Hey I have pushed an update to Google Play regarding reconnect not happening. Do check it out and let me know.

**Comment by motir** [comment]
Just tested it and it is finally fixed!!
Kudos, you've nailed it!

- Moti

**Comment by dc297** [comment]
Great! Closing this issue.

**Comment by trisk** [comment]
Thanks for the fix, but I'm still seeing this after the last update:
```
2017-09-21 12:30:20 WARNING (MainThread) [hbmqtt.broker] Client 1506014967349b140e4445 is reconnecting too quickly, make it wait
2017-09-21 12:30:21 WARNING (MainThread) [hbmqtt.broker] Client 1506014967349b140e4445 is reconnecting too quickly, make it wait
2017-09-21 12:30:22 WARNING (MainThread) [hbmqtt.broker] Client 1506014967349b140e4445 is reconnecting too quickly, make it wait
2017-09-21 12:30:23 WARNING (MainThread) [hbmqtt.broker] Client 1506014967349b140e4445 is reconnecting too quickly, make it wait
```
Reconnect interval is set to 120 seconds.

**Comment by dc297** [comment]
Hey I am not sure if this is an issue with MQTT Client or hbmqtt. Could you try some other app and test if you encounter the same issue?

**Comment by dc297** [comment]
Closing as no activity.
